title: Chukwuemeka Ezeliora
description: >-
  Cloud & DevOps Enthusiast | Final-Year Computer Science Student | AWS • Docker • GitHub Actions • Monitoring Systems 
url: "https://github.com/Therook-sudo/Therook-sudo.github.io"
github_username: Therook-sudo

theme: jekyll-theme-minimal
logo: /assets/img/avatar.png
show_downloads: false
