title: Chukwuemeka Ezeliora
description: >-
  Cloud & DevOps Enthusiast | Final-Year Computer Science Student | AWS • Docker • GitHub Actions • Monitoring Systems 
url: "https://github.com/Therook-sudo/Therook-sudo.github.io"
github_username: Therook-sudo

theme: jekyll-theme-minimal
show_downloads: false

# Link to your custom CSS
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0
sass:
  style: compressed

